language: node_js
node_js: 8.10.0
cache:
  apt: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: git.coding.net
script: hexo clean & hexo generate
branches:
  only:
  - source
env:
  global:
  - secure: c0XEuUGTJmisOc6DTzE7XGC+Sg33a54jvLVgzOkMAZUVWy6WgWhwKEwYV4M0Ycxr1CNy7wrwoQXlRHPEpd51hVJRmEBujWqUs4okkq+755T0gAq2lQnm4UsBy8a361jYTnLsk4Qev4kSju44gbMMpFhiu1oPooO5Trlx7dkQFNhW8rHQTo/CLSl/m/84U8B1eOZnrdXICe2yTuteJ4S4DUu9YrKJw1GZRSYRXYzX4fo0BEUgYHy5ysnBygpmyjaRHHSSJX7gKAv1dJYU83itW202dZ/Xbu03T1XlSXIYwkRQWHVWo4FSpCVdwncUiRyeUdeoxrXOfB7J+IeUwevdtMNucBBLvCEPLMqsUtITn7XzcWiO4ycGYBJQ1ny8mKQsZDai0Er9C3C6JNwTp6x5NqYBlLbnEzD1yyiZj5K4U4uZMEe0dooJAeECGlIjuXmyC4z1SoPBWSLEAqNCRO3Z3uyk9jenT5wEQZI8KE6ap/h/aICGEh6egHbVKvI54SEdU8Qkonr0tedXTAiwRQwB3mHbySF8Q9oYzsMDBjsDni8paSuxOivfW6gCn8uV9U//eT4GKCEJkc6vNZ8tjilA7ziBbqcoWBwBE0TK95YFrl0LeZLuqbGMkV7VhATQBI2NjIo3WckSizG8YIdRVdJ3sJZTjIw7CIFakmN+7XI3izU=
  token:
    secure: AHhlpLNrlugENR6LxPDFjtCpj2gFKlhGk06Z6ZBQqryDozjxs9h2S6wY//Q270/XhfaBrX2BsUsiajgB+zO0PGS2LGsJNCp7JdGDGgkHZtiX5VsN0Rs3w8YKtwttv0MWtGg3PBwdCO+pRgDsTIGniaOI1a5Und3rptbWZBSTE3pnZ9mOmq1GA1CpkC5srGd7QyfJ2zUmAC6tINr9nFv7BScw0224Mz2MZB46yPxwPTOSkMgFoL1XuM1/XbBHLyubCy9bnjqab57/PQc63UT8+xjI0V/2QInZA/N7UXHKQsMzPnxYOPxbg7sTUzMIUzAoDRl3XvzZ/CaCGKSUC4mE0xpRsY68lzjKgJXCVbgFrAvjOyOKdbhvNY8Lnl/ZiY2UiR1dB6SzozUlADWb27K6lXbDjSwzkd/cJeuPZCOKxD1zo+lxzz/TwenT2+K2jC/aj91bwSdeg6jsRy81szaAYQSEDaRf+kPSXmTaLdO1NMIDsH6GMjRWWYOakjNCnrHpIldjn2dK1MnVPIej5j05uPEAqo+ywoFE4j8tE7A1GBf5zy9xgPF0KqvWBi+Kkgs/hA2oE8PYsc2hxTm2QsuOlo5Nm/VmqmqBjEFX773BJKMTvck7En9GPTMUHfNEndS4wmE0ljF7Arqk/RPRiadfX8r7GHoJiA1MJorAth8nZOs=
before_install:
- openssl aes-256-cbc -K $encrypted_6a5d0d2bb8ce_key -iv $encrypted_6a5d0d2bb8ce_iv
  -in .travis/4gcwgo.enc -out ~/.ssh/4gcwgo -d
- export TZ='Asia/Shanghai'
deploy:
  provider: script
  script: sh .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: source
after_deploy:
  - firebase deploy --non-interactive --token $FIREBASE_TOKEN
