# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 日新知 
subtitle: 知行诺一
description: 易知 简能
author: zhinuo
language: zh-CN
timezone: Asia/Shanghai


# custom Site settings
# more detail check out docs
SEOTitle: 日新知 日新 知行诺一
header-img:  # header-img.png 
email: imovomi@gmail.com # your email
keyword: 日新知 日新 知诺 知行诺一 # your keywords
# custom end


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.rixin.site
root: /
permalink: article/:abbrlink.html    # :category/:abbrlink.html    # :category/:id.html    # :id-:title.html
permalink_default:
  lang: zh-CN

# Header
menu:
  Home: /
  categories: /categories
  tags: /tags
  Rss: /atom.xml    #  /rss2.xml

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ""
    permalinkBefore: false

# Category & Tag 分类项为 单字 时 且 lang: zh-CN 下面的英语为翻译
default_category: uncategorized
category_map:
    记: writing
    悟: spark
    经: essence
    摘: excerpt
    杂: MISC
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日 @ HH:mm
time_format: HH时mm分


pagination_dir: page


jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
    
# Extensions
## Plugins: https://hexo.io/plugins/
Plugins:
- hexo-generator-sitemap
- hexo-abbrlink
- hexo-deployer-ftpsync
- hexo-blog-encrypt
- hexo-baidu-url-submit
- hexo-cli
- hexo-deployer-git
- hexo-generator-archive
- hexo-generator-category
- hexo-generator-feed
- hexo-generator-index
- hexo-generator-json-content
- hexo-generator-json-feed
- hexo-generator-seo-friendly-sitemap
- hexo-generator-tag
- hexo-renderer-ejs
- hexo-renderer-less
- hexo-renderer-marked
- hexo-renderer-stylus
- hexo-server

# Miscellaneous
# links:
  # 知诺备份: http://www.zhinuo.space/ .托管于 openshift 上，基于 wordpress，优点是主题个人比较喜欢，缺点是速度和稳定性都很一般。

## Themes: https://hexo.io/themes/
# theme: miccall
theme: hiker
# theme: skapp

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: # github coding 同时部署  多个 deploy 要使用 — type
- type: git
  repository: 
    github: git@gitwgo:wego0/wego0.github.io.git,master   
    coding: git@codingwgo:wegoo/wegoo.git,coding-pages
- type: baidu_url_submitter
# deploy:
  # type: ftpsync
  # host: 192.168.98.101
  # user: wego
  # pass: 3155
  # remote: /MF/www/hexowgm
  # port: 2221
  # connections: 1
  # verbose: true

# encrypt https://github.com/edolphin-ydf/hexo-encrypt
# encrypt:
  # # pwdfile: encrypt_password     # this store the password in a file, the whole content of this file will be regarded as the password
  # password: 3155 # this set password here
  # # replace_all_url: true # this will replace img url in all posts
  # # base_url: http://you img base url/    # this will connect with you img url in you post, except full url(start with http://)
  # # qiniu_ak: your qiniu access key 
  # # qiniu_sk: your qiniu secrect key 
  # # img_url_ttl: 86400000  # 3600 second, the ttl for qiniu img url
  # type: base64 # or qiniu , if base64, the base_url, qiniu_ak, qiniu_sk and img_url_ttl is unnecessary

# Security
## https://github.com/MikeCoder/hexo-blog-encrypt 密码不能为纯数字 1.1.10版已修正
encrypt:
  enable: true
  default_abstract: 本文已隐藏, 请输入密码浏览.</br>
  default_message: 您好, 请输入密码浏览.

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex
  # crc32 & hex e.g. https://post.zz173.com/posts/8ddf18fb.html
  # crc32 & dec e.g. https://post.zz173.com/posts/1690090958.html

baidu_url_submit:
  count: 3 ## 比如3，代表提交最新的三个链接
  host: www.rixin.site ## 在百度站长平台中注册的域名
  token: L4PiiYWHNRZdoIF8 ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址，新链接会保存在此文本文档里

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# https://github.com/hexojs/hexo-generator-index
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 30
  yearly: true
  monthly: true
  daily: false

# https://github.com/hexojs/hexo-generator-category
category_generator:
  per_page: 10

# https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 30

# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom     # rss2
  path: atom.xml # rss2.xml
  limit: 100000

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml

# https://github.com/ele828/hexo-prism-plugin
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'default'
  line_number: false    # default false


restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         # 分类数据
  use_category_slug: false # Use slug for filename of category data
  tags: true               # 标签数据
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 文章数据
  pages: false             # 额外的 Hexo 页面数据, 如 About


generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path:   sample/sample-logo.png
    width:  600
    height: 60
  substituteTitleImage:
    path:   sample/sample-substituteTitleImage.png
    width:  1024
    height: 800
  warningLog: false   # To display warning, please set true.
  generateAmpPath: amp/article/:abbrlink.html